<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Choose user</name>
   <tag></tag>
   <elementGuidId>e4d888c9-48f7-4e83-9ad9-e1f50dddec08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b7-b6-$b4']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ThemeGrid_Width10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55711e28-d471-438a-b948-570a08a36fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_Width10</value>
      <webElementGuid>7562d2af-f4c2-4fe4-b28f-70982d0197af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose user</value>
      <webElementGuid>5610e589-4918-4d5b-bcbf-d214b83a1a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b6-$b4&quot;)/div[@class=&quot;position-relative OSInline&quot;]/div[1]/div[@class=&quot;custom-dropdown-searchName&quot;]/div[@class=&quot;ThemeGrid_Width10&quot;]</value>
      <webElementGuid>e23296df-18b3-4c6a-8012-3a47041ab22b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b6-$b4']/div/div/div/div</value>
      <webElementGuid>75c9a1a3-45cb-4fa5-ae8f-f3e6b55cc021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::div[7]</value>
      <webElementGuid>e84bb85a-9d54-4da1-b0d1-ae3a09be81ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::div[10]</value>
      <webElementGuid>4f032e2a-4411-402f-b399-798046473c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discard'])[1]/preceding::div[7]</value>
      <webElementGuid>2150e176-7a9b-43f9-936a-015128466835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>9dfd7e6f-3b46-4447-80fe-0fd9b907558a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Choose user' or . = 'Choose user')]</value>
      <webElementGuid>aa209084-c2eb-43c6-b56a-888129eacfe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
