<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose user_b7-b6-b4-Input_Search_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>fd956d68-4d8c-47de-9d91-de89a1d73e4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b7-b6-b4-Input_Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b6-b4-Input_Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3baf216b-c3af-4489-8d80-741b810c01d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control padding-left-xxl OSFillParent</value>
      <webElementGuid>b7280f89-10dc-4644-b585-66ae0590e6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13ed57f2-189f-454a-adcd-8af6bf8d6f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TED </value>
      <webElementGuid>335da79b-fea3-4571-83a0-b66857de93fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e5f269e-0269-49e7-827f-773ab2c80b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>52bbfd47-c5cc-4df2-b767-b425500e81dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TED </value>
      <webElementGuid>71dfdbbc-d2c9-4fbb-a829-8795bef419c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b6-b4-Input_Search</value>
      <webElementGuid>047a03d8-a7b2-461b-8e49-4e5b5dfca8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b6-b4-Input_Search&quot;)</value>
      <webElementGuid>c2cdde54-1e2f-4de2-a779-e6e3d8629c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b7-b6-b4-Input_Search']</value>
      <webElementGuid>9e98fa52-3313-44d5-b4af-4a4a1c980112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b6-b4-b2-Input']/span/input</value>
      <webElementGuid>b8fdabb0-0772-403f-a49d-61cb15e45c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2dc15bc4-1b62-44f6-9017-fed479c54f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'TED ' and @id = 'b7-b6-b4-Input_Search']</value>
      <webElementGuid>667947b0-b408-4a32-9724-e44992e11e13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
