<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose user_b7-b6-b4-Input_Search_1_2</name>
   <tag></tag>
   <elementGuidId>875b9580-86aa-4846-b2dd-33234abf1f4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b7-b6-b4-Input_Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b6-b4-Input_Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ac2666d-6eac-4bcb-9def-8d5480534b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control padding-left-xxl OSFillParent</value>
      <webElementGuid>9f264d59-f112-4e7c-a622-591d3cf68d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84cf0513-fd13-4747-a835-73be2b52f908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TE</value>
      <webElementGuid>0e62d17d-c75d-4a1a-826f-d7ebe19ae808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>be6d8950-76dc-437b-9386-14550a3c0aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3528f3e2-7352-40fb-b7e6-37a525c7706c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TE</value>
      <webElementGuid>245cb2a5-9faf-483e-831a-c6779a7b789e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b6-b4-Input_Search</value>
      <webElementGuid>4082a37a-41c9-4f3c-a4bd-6d57c8db585a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b6-b4-Input_Search&quot;)</value>
      <webElementGuid>0c190121-1697-4870-84cc-802435ba5e88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b7-b6-b4-Input_Search']</value>
      <webElementGuid>6f96e8a2-9e72-447b-8496-cb7c4c95caba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b6-b4-b2-Input']/span/input</value>
      <webElementGuid>35c65ae9-a443-4539-8919-fcc614c9e452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c35b1b2f-a1e1-4c02-8a01-3c86190eaa5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'TE' and @id = 'b7-b6-b4-Input_Search']</value>
      <webElementGuid>ee0c51ea-ea73-4f5d-aacb-525259d671e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
