<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_P</name>
   <tag></tag>
   <elementGuidId>f123dd3c-8e85-45d3-9033-725ad5412d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b7-b6-b1-TextArea_Value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b6-b1-TextArea_Value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>103178c7-52d7-485f-bd0d-24dad87bea5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control margin-none-important message-fix OSFillParent</value>
      <webElementGuid>cfd76ebb-5127-4a63-9102-c66c310cca3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9e359d5f-b2ba-42ba-9483-2ef4cfad03a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>This item is recommended</value>
      <webElementGuid>625e7110-2260-45a3-8683-2472020f5483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b6-b1-TextArea_Value</value>
      <webElementGuid>2dc72d7c-8b9f-4002-b150-6cf4f5d3fc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>b75970ba-15aa-437c-b864-664b40004fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>629dd70b-3fb3-4002-9c85-bc8d8f012772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b6-b1-TextArea_Value&quot;)</value>
      <webElementGuid>45ee90ae-1eae-4499-a414-b2c12bb1ec68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b7-b6-b1-TextArea_Value']</value>
      <webElementGuid>1dc52f07-16ae-450f-982c-a97336c860ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b6-$b1']/span/textarea</value>
      <webElementGuid>4ddad1c1-906a-4dd0-bc83-6cb7dff9e4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::textarea[1]</value>
      <webElementGuid>c4772f01-4562-40cf-a830-f4145f61c307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit for Approval'])[1]/following::textarea[1]</value>
      <webElementGuid>244983c7-f9b0-4669-aa05-01a4ee0fa687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::textarea[1]</value>
      <webElementGuid>2a1e9e3f-8cc3-42be-9e87-7eb75198bd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TED POPS'])[2]/preceding::textarea[1]</value>
      <webElementGuid>8df065c0-f5bd-472c-8537-2275faf7142f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='P']/parent::*</value>
      <webElementGuid>c1db39b4-c385-48bc-8ec8-bf8fc0e5fcc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/form/div/div/span/textarea</value>
      <webElementGuid>d18c9adc-6b2a-4645-956a-d1643d88b2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'This item is recommended' and @id = 'b7-b6-b1-TextArea_Value' and (text() = 'P' or . = 'P')]</value>
      <webElementGuid>b2f9a73a-1478-4103-a484-6ad5a067dc90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
