<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Award justification_b19-TextArea_Value</name>
   <tag></tag>
   <elementGuidId>de8a68df-8dbc-4e3a-aa8c-e9279be1943b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b19-TextArea_Value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b19-TextArea_Value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>847a2304-7a76-4866-a2eb-8b84635b3cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control margin-none-important message-fix OSFillParent not-valid</value>
      <webElementGuid>a29a93ab-9e70-4f7e-a9e4-ac5e9548af80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e3a7de98-da26-4e3f-a834-4f56f84cfaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter description</value>
      <webElementGuid>7f204f33-9676-4b84-b3ab-6c8b2a661fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b19-TextArea_Value</value>
      <webElementGuid>ed9ee453-74b7-4d5e-aeac-a597945f0c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3000</value>
      <webElementGuid>d80023c6-b393-47a3-a20c-4a3e2b21348e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b19-TextArea_Value&quot;)</value>
      <webElementGuid>4e11770a-af44-4c8a-81ba-bb8e7739e856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b19-TextArea_Value']</value>
      <webElementGuid>df042af4-e549-4d6d-b425-705065c72d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b19-TextInput']/span/textarea</value>
      <webElementGuid>380da760-62f5-4337-9426-8d4211d32499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>375b6bfe-a307-4daa-95a9-de224a4a2371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Please enter description' and @id = 'b19-TextArea_Value']</value>
      <webElementGuid>7a681a79-7866-4a92-af4e-48e91870b63c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
