<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_p</name>
   <tag></tag>
   <elementGuidId>5c6c6f17-82d6-48c9-b748-fa94e9a53f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b7-b15-b1-TextArea_Value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b15-b1-TextArea_Value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c4b75b2b-7732-4cf5-96f6-9508c4b4d1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control margin-none-important message-fix OSFillParent</value>
      <webElementGuid>80a52e48-722a-4e5f-9a56-4bd719ae170b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e57b29ac-d5fd-4163-b897-9c458514e150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>This item is recommended</value>
      <webElementGuid>164972b9-5dbb-4b33-90eb-419933734da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b15-b1-TextArea_Value</value>
      <webElementGuid>8a2ca9c7-71d4-4526-af43-2bcc1b458e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3000</value>
      <webElementGuid>8731d9d9-3418-427c-8851-8d8e58df2c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a2effa0e-43ad-40ff-a200-a8233d9fd164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b15-b1-TextArea_Value&quot;)</value>
      <webElementGuid>cd34598f-1f7a-4f06-b4fa-67687b0127e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b7-b15-b1-TextArea_Value']</value>
      <webElementGuid>14c77451-940b-4cd3-84cb-af0302a15782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b15-$b1']/span/textarea</value>
      <webElementGuid>e5087a2f-fa07-4239-aea1-60f7e1f921b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::textarea[1]</value>
      <webElementGuid>fa015814-aed2-4189-b48f-08f01ef07b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete Approval'])[1]/following::textarea[1]</value>
      <webElementGuid>b9803f9b-a67e-4c79-9546-1e4dfbde2012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>5b023521-467d-4316-a9ee-43afdddbac9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a02a0d9d-7dc1-40b3-9df6-a13b54f261ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='p']/parent::*</value>
      <webElementGuid>29f7dc5f-cbf5-48e0-adf8-73bd74e5a365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/form/div/div/span/textarea</value>
      <webElementGuid>ff6be1d2-d07a-4964-897b-e55cb0a4ab92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'This item is recommended' and @id = 'b7-b15-b1-TextArea_Value' and (text() = 'p' or . = 'p')]</value>
      <webElementGuid>7569bd33-91cf-46b5-a547-7c8035a702ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
