<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LIZ POPS</name>
   <tag></tag>
   <elementGuidId>3cb1a1a0-e330-4725-a525-725a87f35c2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='b7-b4-Form']/div[4]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.margin-top-xl > div.OSInline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5443f8e2-0f38-4166-b2f1-cb96a89d273a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSInline</value>
      <webElementGuid>229af96f-b6e7-46f7-93ab-ad602c48c97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LIZ POPS</value>
      <webElementGuid>60e47662-34a1-4de5-9f16-df35475383eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b4-Form&quot;)/div[@class=&quot;margin-top-xl&quot;]/div[@class=&quot;OSInline&quot;]</value>
      <webElementGuid>3956fa32-f7d7-440e-813e-30a215fd8c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b7-b4-Form']/div[4]/div[2]</value>
      <webElementGuid>55cd9c84-0173-45ed-8bdc-127a92803507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluator (1/15)'])[1]/following::div[1]</value>
      <webElementGuid>65eb995e-2117-437c-bb7f-244de2409bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='please'])[1]/following::div[4]</value>
      <webElementGuid>d6370c54-c1be-4061-9c59-5df14348d162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add user'])[1]/preceding::div[11]</value>
      <webElementGuid>1998055e-ab22-4f65-8bdd-cd49979f137a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div[2]</value>
      <webElementGuid>4dfeffa8-87fa-472d-98a6-e345422da84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LIZ POPS' or . = 'LIZ POPS')]</value>
      <webElementGuid>5c1eec8f-dfbb-462b-a0ed-90a4bf327483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
