<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose user_b7-b4-l1-476_0-b5-Input_Search_1_2</name>
   <tag></tag>
   <elementGuidId>49a87465-30d0-47e0-a568-86c4faa2e239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b4-l1-476_0-b5-Input_Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abe91a4b-9496-4669-a10e-146a87a006ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control padding-left-xxl OSFillParent</value>
      <webElementGuid>c057a38d-3831-498f-8503-ed22091ac541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef894309-df31-42de-a668-951721335b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>LI</value>
      <webElementGuid>8642c09e-ddbb-463c-83ad-ad96fc1bee99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82fe7480-f9dd-45bb-93ed-daa3e73a25be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8f273ad2-195f-4c56-a801-05c67d2272aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LI</value>
      <webElementGuid>289cc4b7-eb9c-403a-aaac-87d0953e0650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b4-l1-476_0-b5-Input_Search</value>
      <webElementGuid>e38832e4-52cc-4391-b1bc-d94fc59a90bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b4-l1-476_0-b5-Input_Search&quot;)</value>
      <webElementGuid>a9305ec6-f77a-45a2-b31c-8d053c76ec58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>ddc857fb-40ae-40d4-824d-90c8e5f08bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b4-l1-476_0-b5-b2-Input']/span/input</value>
      <webElementGuid>e416f7dd-69c1-462c-b6f4-2b3317dc29c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>69078195-e3f0-45d8-8554-0d8d7016d4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'LI' and @id = 'b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>f257a6f5-3511-4011-bd0d-dbedf25806f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
