<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose user_b7-b4-l1-476_0-b5-Input_Search_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>710e8656-cf02-44d2-aa1d-bd6fa9fb6e95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b4-l1-476_0-b5-Input_Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4eb65683-3591-4fee-bd2e-5b8b5e407e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control padding-left-xxl OSFillParent</value>
      <webElementGuid>decbedda-db79-4a4c-922c-ee670430f92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7fa34d30-e6a7-4768-8c54-934414c45620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>LIZ PO</value>
      <webElementGuid>963efab5-d8f4-43fe-aef3-af3b78d14c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e825e3e-1056-4362-8fc8-3e9bb8387830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>edb5ec6b-2390-4e96-a140-31161d623ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LIZ PO</value>
      <webElementGuid>6618119b-0a95-4a93-b164-4146f550361c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b4-l1-476_0-b5-Input_Search</value>
      <webElementGuid>ac76d879-b4f8-433e-8bd9-512d693f8cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b4-l1-476_0-b5-Input_Search&quot;)</value>
      <webElementGuid>f73b6463-4770-4256-9765-4688002dbb03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>714f0fdc-7753-4dee-9c27-b063f8560a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b4-l1-476_0-b5-b2-Input']/span/input</value>
      <webElementGuid>7eef3499-a41f-4584-a342-bbfce75cf2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>497d7782-d667-4ad4-b9af-c8fbec333f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'LIZ PO' and @id = 'b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>64d3b19a-ce64-4a70-b09d-f5883573bc69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
