<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose user_b7-b4-l1-476_0-b5-Input_Search</name>
   <tag></tag>
   <elementGuidId>a2f06f0c-6a2f-45ee-a03c-749ae4edf9fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b4-l1-476_0-b5-Input_Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fb61c5d-d1b4-4658-be9b-7b486145da30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control padding-left-xxl OSFillParent</value>
      <webElementGuid>66933cb7-6cc9-4378-8f03-1efe8bd974ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dbdd40d-74df-4d4c-8a2b-76732e616a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing to search</value>
      <webElementGuid>6d62f315-701d-49c3-a254-bfd117f63c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>907bd44c-df89-447d-98c1-ac88f7a2f58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5fdea280-6f87-442d-a60f-912953e79165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b4-l1-476_0-b5-Input_Search</value>
      <webElementGuid>500fe069-0612-4dfe-b894-f4c9afa5a6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b4-l1-476_0-b5-Input_Search&quot;)</value>
      <webElementGuid>721152bc-cf3c-4652-b2d7-fc004ecfc84a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>c7a5c4f0-e4c0-43b8-a501-e29b291828b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b4-l1-476_0-b5-b2-Input']/span/input</value>
      <webElementGuid>2184a213-88a0-4a00-aa52-e9404e07630f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>2e6a634c-be4b-4096-9368-fbd3b75c2c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Start typing to search' and @id = 'b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>d6f29aa5-8006-45e7-9e77-9941580fe3eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
