<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose user_b7-b4-l1-476_0-b5-Input_Search_1_2_3</name>
   <tag></tag>
   <elementGuidId>3904ff63-43fc-497b-a8b7-75c20ae0aaab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b4-l1-476_0-b5-Input_Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e110a089-3cd9-4ce2-bcee-630b4e15def2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control padding-left-xxl OSFillParent</value>
      <webElementGuid>2197edb6-740d-415a-ba44-4acccc961dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0979be8e-b45a-4332-b58f-e70eb09de447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>LIZ</value>
      <webElementGuid>67f11347-8bd8-41a6-a27f-747371304d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e37b91a0-e9ff-46d6-932f-00fd06c423db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>552216cb-db00-42fe-ab71-38ea7a81c0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LIZ</value>
      <webElementGuid>c5874368-d207-4896-b86b-ddcd1fc35ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b4-l1-476_0-b5-Input_Search</value>
      <webElementGuid>4c305d15-5c02-4294-9d8c-dabe200409e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b4-l1-476_0-b5-Input_Search&quot;)</value>
      <webElementGuid>6e68b0f2-6b1e-420b-8594-26d5e38dcb60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>5fcb3379-2643-492c-9789-535031e8a0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b4-l1-476_0-b5-b2-Input']/span/input</value>
      <webElementGuid>a0e57497-17e3-4ec3-a29d-8c3e61e043b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>6da77a32-af30-4c65-9f76-8ebf350ae64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'LIZ' and @id = 'b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>2a2c973b-476c-41a2-81ea-11b598ef057a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
