<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PR Release Date_b10-l1_0-87_0-Checkbox1</name>
   <tag></tag>
   <elementGuidId>2b39a688-97af-4d68-b123-d8b52246d1d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b10-l1_0-87_0-Checkbox1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox' and @id = &quot;b10-l1_0-179_0-Checkbox1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ce3c996-439f-4c3f-b240-7d803e30c0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2909f66b-c6c4-4b2f-b696-da80ed14cda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>86f598ad-0779-4151-a662-3ef5ef11c48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b10-l1_0-87_0-Checkbox1</value>
      <webElementGuid>23e3e9f8-79c5-4b9e-94fd-5e8d2106febc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b10-l1_0-87_0-Checkbox1&quot;)</value>
      <webElementGuid>ed106b98-d881-4f6e-ad44-9d03a39203e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b10-l1_0-86_0-Checkbox1']</value>
      <webElementGuid>7f347864-b082-4268-9d30-e4b1e2047f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b10-b10-Content']/table/tbody/tr/td/span/input</value>
      <webElementGuid>4599fb38-2c55-4c3b-aeba-98f5d295ffb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>2bfb05b9-560b-4fec-a952-e88888c21260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b10-l1_0-86_0-Checkbox1']</value>
      <webElementGuid>86a142cb-55a7-4cab-8b6f-8213ae4ae220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
