<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose user_b7-b4-l1-476_0-b5-Input_Search_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>02c76327-7adc-4887-ae5f-988220b89cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b4-l1-476_0-b5-Input_Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ed2aa8e-68a6-49aa-86ee-afab6f8f6be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control padding-left-xxl OSFillParent</value>
      <webElementGuid>e9f9cfa0-f5db-4fb6-94d6-64f20ed41bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8aec0af1-ee90-4697-9a8c-460d33f80d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>LIZ POP</value>
      <webElementGuid>6375648d-4d6b-4dfd-a996-8e684ddb5a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8374ed1-667f-4d00-a9d9-736fb1c5d709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0d297d23-b555-4d10-814b-d7af7a6ff3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LIZ POP</value>
      <webElementGuid>ed372395-0f07-4cf1-b0d4-9c6d0c656ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b4-l1-476_0-b5-Input_Search</value>
      <webElementGuid>e256e2ad-5560-4208-bf7d-03da31041d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b4-l1-476_0-b5-Input_Search&quot;)</value>
      <webElementGuid>843eecd4-cd94-436c-b62c-7c416e7b3405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>f206de05-7129-4cae-9c5d-b70afbe7eb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b4-l1-476_0-b5-b2-Input']/span/input</value>
      <webElementGuid>7560c7f9-de3f-49ef-8b65-2a728c7297f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>67aeb1c8-0508-4346-a6db-eac622a1787c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'LIZ POP' and @id = 'b7-b4-l1-476_0-b5-Input_Search']</value>
      <webElementGuid>f45ade19-2cbc-4725-8a2f-f9b4a06b85ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
