<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Recommended by buyer_btn myprocure-b_bfb2f9</name>
   <tag></tag>
   <elementGuidId>7e92af4c-fa3a-4214-9c58-a39461c2eddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.myprocure-btn-secondary-medium.OSFillParent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>430ce293-d38e-477f-8c8c-d9ad98abdd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn myprocure-btn-secondary-medium OSFillParent</value>
      <webElementGuid>430fceb0-8a66-45db-b57a-d39463eb6132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0db732c-6c46-4162-b78b-602dddf33af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b58-l1-168_0-b1-Column1&quot;)/button[@class=&quot;btn myprocure-btn-secondary-medium OSFillParent&quot;]</value>
      <webElementGuid>471ebf21-646c-42b7-93a0-930c40d38d18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>ae76dfd1-35f6-4c72-a6d3-b04bbb05d05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b58-l1-168_0-b1-Column1']/button</value>
      <webElementGuid>419bb0b1-352a-41e1-bc18-375ad6da2eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended by buyer'])[1]/following::button[1]</value>
      <webElementGuid>c91d095d-656b-46a9-9d51-7485dc358883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WIDTH'])[1]/following::button[1]</value>
      <webElementGuid>90af69c7-4a91-413c-ad5d-832829ff610f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BEARING,BA,6309,MTRC,RADL CNTCT,6300,DG'])[1]/preceding::button[2]</value>
      <webElementGuid>d669917b-5885-4cd6-b97d-87e1f4071959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::button[2]</value>
      <webElementGuid>b2749e1f-e245-4ab1-a235-24b610644dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>f69781d7-7bdd-412f-8a0d-94c38d908514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>7dbfc700-2a90-41e1-a14f-a63f1612151c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
