<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accepted</name>
   <tag></tag>
   <elementGuidId>a8684edf-7024-4018-a9b4-79deebcf845e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b58-l1-186_0-TechnicalAcceptance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b58-l1-186_0-TechnicalAcceptance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f24dba37-d77a-4294-a295-2267151085b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProductDetails-details-container-item background-containerComparePage</value>
      <webElementGuid>77a49bc0-1312-4838-a290-9c3975766d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b58-l1-186_0-TechnicalAcceptance</value>
      <webElementGuid>f8b441c8-f987-4311-a7a6-b1c6cea0339d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepted</value>
      <webElementGuid>b2b783da-39b2-480e-840f-7d795fedbb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b58-l1-186_0-TechnicalAcceptance&quot;)</value>
      <webElementGuid>a60a6060-2c11-45af-8871-23b86a5d4c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b58-l1-186_0-TechnicalAcceptance']</value>
      <webElementGuid>6d19ee0e-88c3-43d2-8efc-41de3780e235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b58-l1-186_0-ItemContainer']/div</value>
      <webElementGuid>2f0fdf1f-e6f5-4821-8a8b-0ac8d5cc01f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BEARING,BA,6309,MTRC,RADL CNTCT,6300,DG'])[1]/following::div[2]</value>
      <webElementGuid>793e98b6-aef5-4dde-8db4-cd3848a5b682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended by buyer'])[1]/following::div[10]</value>
      <webElementGuid>c82b9afd-08ba-4511-b0c0-db64a8cbbfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::div[7]</value>
      <webElementGuid>6b2bd0a7-dead-42eb-a448-7350baaccf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>02d0047b-4106-4bb5-8296-df800b51d7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b58-l1-186_0-TechnicalAcceptance' and (text() = 'Accepted' or . = 'Accepted')]</value>
      <webElementGuid>227934c6-8ce8-4a50-93ae-c73afbdf27a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
