<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_reject</name>
   <tag></tag>
   <elementGuidId>5e23677a-025b-425c-bc6a-2c9a0bd4503d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b58-l1-186_1-b3-Tooltip']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b58-l1-186_1-b3-Tooltip > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a372e53-1033-47b2-9a91-3ac064f7cf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>reject</value>
      <webElementGuid>d0b91366-cfd7-4688-94c5-5262e7c24772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b58-l1-186_1-b3-Tooltip&quot;)/span[1]</value>
      <webElementGuid>efc70ac7-8f04-47c5-b470-30bd5aafd85d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b58-l1-186_1-b3-Tooltip']/span</value>
      <webElementGuid>aaa6c1ef-23e0-4875-8ca6-1240dcc7dc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='METRIC,RADIAL CONTACT'])[3]/following::span[4]</value>
      <webElementGuid>71af2294-1e3e-4b44-9a5d-0d6de2bdb8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEEP GROOVE'])[3]/following::span[6]</value>
      <webElementGuid>1d214050-2cea-4cbc-8bdf-24bf1da77ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b58-l1-186_1-b3-Tooltip', '&quot;', ')/span[1]')])[1]/preceding::span[1]</value>
      <webElementGuid>2b825c27-9d19-4bb6-9ae9-ae4864e0df3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='reject']/parent::*</value>
      <webElementGuid>9445b1b9-b421-4432-90a9-763313ee5b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>8911990f-5eda-4d1d-9b1c-343611e0f585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'reject' or . = 'reject')]</value>
      <webElementGuid>abd8e8e5-89d0-4184-9aa9-82a23dcb313c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
