<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_reje</name>
   <tag></tag>
   <elementGuidId>08036865-bc87-460b-a5bf-f551fc7fa4fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b58-b9-b2-TextArea_Value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b58-b9-b2-TextArea_Value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>af8669df-cbf3-4f6f-b580-521603f0eb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control margin-none-important message-fix OSFillParent</value>
      <webElementGuid>5ec01857-8452-4e64-a80f-b5209ff2a982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d36337c3-82ca-4d06-afe2-413a6c148b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>This item is recommended</value>
      <webElementGuid>c3882d19-52b3-44e4-a4d9-fe38fd32da45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b58-b9-b2-TextArea_Value</value>
      <webElementGuid>7d2edec9-f8d8-4928-acfe-e0e311bc1d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3000</value>
      <webElementGuid>51ee4fce-411f-4486-a8cb-b096d71ba40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>reje</value>
      <webElementGuid>3ec25b3f-a1fb-42af-b542-700f212f059e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b58-b9-b2-TextArea_Value&quot;)</value>
      <webElementGuid>eadfcf69-4f5f-428f-a413-d290a15d7199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b58-b9-b2-TextArea_Value']</value>
      <webElementGuid>b8fcd079-efc4-4292-8982-3192801c9d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b58-b9-$b2']/span/textarea</value>
      <webElementGuid>46e81480-d1ed-40c7-b1b8-fdd00ce42852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::textarea[1]</value>
      <webElementGuid>a8a568a3-4572-4b7a-a69e-1054fa30ab34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluator Remarks'])[1]/following::textarea[1]</value>
      <webElementGuid>f3626fba-b966-4874-862f-daa4f5b93a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4eb627a8-d825-4cf3-b9d7-fe93000c391e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='reje']/parent::*</value>
      <webElementGuid>40c0fd6f-4c84-4342-a4ec-279f97eaca9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>94d8f046-18c1-415a-be61-730f6e9455cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'This item is recommended' and @id = 'b58-b9-b2-TextArea_Value' and (text() = 'reje' or . = 'reje')]</value>
      <webElementGuid>75291772-f531-4e95-a10e-6234e5dd9a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
