<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remark_b7-b16-b2-TextArea_Value</name>
   <tag></tag>
   <elementGuidId>365788dc-623e-4162-93bd-d0b0a5b8c5d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b7-b16-b2-TextArea_Value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b16-b2-TextArea_Value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3209f420-1087-49fa-ae87-03833ed9da52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control margin-none-important message-fix OSFillParent</value>
      <webElementGuid>e3dfa1bb-fefe-431b-80a7-7ae2aef39f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4f05dd6b-3136-4a10-852d-433d8b625bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>This item is recommended</value>
      <webElementGuid>c4a35476-ded3-468a-aa1e-22215568950c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b16-b2-TextArea_Value</value>
      <webElementGuid>848df11a-c149-4ffd-80d1-de69d7f843d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3000</value>
      <webElementGuid>249c822c-912e-4686-9a2d-30a511677339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b16-b2-TextArea_Value&quot;)</value>
      <webElementGuid>5f726289-c915-4ce0-aef4-4279bf6a5fd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b7-b16-b2-TextArea_Value']</value>
      <webElementGuid>b0eb5744-e2a1-4b73-844a-2639dc7c68bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b16-$b2']/span/textarea</value>
      <webElementGuid>7d9c0c96-077c-47bb-9725-10cd8f16f9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>fab29a59-9e46-43fc-ac13-f8ee5da15803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'This item is recommended' and @id = 'b7-b16-b2-TextArea_Value']</value>
      <webElementGuid>a47274d0-3078-4816-8502-81e8cef2409b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
