<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_co</name>
   <tag></tag>
   <elementGuidId>6d2ee851-a9a0-473b-8d46-9b916b70021b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b7-b16-b2-TextArea_Value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b7-b16-b2-TextArea_Value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e740081b-c58d-46f2-913e-a665ea88ee8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control margin-none-important message-fix OSFillParent</value>
      <webElementGuid>16778849-801d-4188-ad1a-48c72a8baede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>754be33d-6d6d-41a6-a916-349e1e0454ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>This item is recommended</value>
      <webElementGuid>2e9092bc-d013-4fc5-b05f-6c9199dbb4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-b16-b2-TextArea_Value</value>
      <webElementGuid>062397c8-c3bf-4f90-b753-af67aee3c6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3000</value>
      <webElementGuid>1a02e9aa-4ac1-4032-9f20-e4103fa2cdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>co</value>
      <webElementGuid>4f39e9d8-3ffe-47a7-a57e-86ae39a451f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-b16-b2-TextArea_Value&quot;)</value>
      <webElementGuid>127357be-de49-4702-a8aa-7b0ac1782e1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b7-b16-b2-TextArea_Value']</value>
      <webElementGuid>67c48d84-62ef-4981-a798-c429773c3c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b16-$b2']/span/textarea</value>
      <webElementGuid>6a1871de-1c59-4839-b3fb-3c4ebeb986cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[1]/following::textarea[1]</value>
      <webElementGuid>998034bf-92d2-4561-994d-b92591248c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete Evaluation'])[2]/following::textarea[1]</value>
      <webElementGuid>f04ed8ff-a17a-4bb9-a89e-60a8230f6f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discard'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3d348fa0-21ab-49b6-88a2-01f93e1cb9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>ab416a8b-9fe6-4fd2-a3c9-5f227cdf8512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='co']/parent::*</value>
      <webElementGuid>9cae699c-a9a5-4488-b4e2-ead51e27a212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3f5bc319-7629-4905-ba7b-0fcf87ae3b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'This item is recommended' and @id = 'b7-b16-b2-TextArea_Value' and (text() = 'co' or . = 'co')]</value>
      <webElementGuid>149eff4c-4c85-45b2-997f-26dd2be0177d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
