<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>acfcbac0-f156-45f1-841f-5cfd2f1b4008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.account-title-ctn.account-tittle.logout-ctn.margin-top-s > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b1-b5-b1-Items']/div/div[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5b06351a-3acf-498a-ae89-f9449940dfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MyProcure/img/MyProcure_CW.Lefticon.svg?YsZc96m5YOfzIsPWBFfSzQ</value>
      <webElementGuid>b2927a15-b415-45ba-b9ed-972468587aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b1-b5-b1-Items&quot;)/div[@class=&quot;sub-menu-user-info display-flex flex-direction-column&quot;]/div[@class=&quot;account-title-ctn account-tittle logout-ctn margin-top-s&quot;]/img[1]</value>
      <webElementGuid>eb3dad10-7cca-4b98-a7aa-0fe8ff3277db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b1-b5-b1-Items']/div/div[4]/img</value>
      <webElementGuid>3b86676d-a16a-4c62-85db-48cec59c666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/img</value>
      <webElementGuid>d5176b2d-b64a-4c45-b1d6-92bf949b327d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/MyProcure/img/MyProcure_CW.Lefticon.svg?YsZc96m5YOfzIsPWBFfSzQ']</value>
      <webElementGuid>12fed8af-2b31-43e5-b433-28fa9c957ac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
