<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Connected to Windows_tile-img</name>
   <tag></tag>
   <elementGuidId>4688c550-5b98-47af-b7fb-d80bdcab534f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otherTile > div.table-row > div.table-cell.tile-img > img.tile-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='otherTile']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>710abd90-1360-4938-a7c8-91f157a64877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-img</value>
      <webElementGuid>75d89a92-15b7-4c7e-8b7b-02f849c02629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>954259ab-e217-49bb-b07d-157b28f4397b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pngsrc</name>
      <type>Main</type>
      <value>https://aadcdn.msftauth.net/shared/1.0/content/images/picker_account_add_387f8dc3a85b573b9b6d74321585afee.png</value>
      <webElementGuid>4a5adad9-adb5-4d2a-891b-42a97c5936c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svgsrc</name>
      <type>Main</type>
      <value>https://aadcdn.msftauth.net/shared/1.0/content/images/picker_account_add_77a852ed38516108ced087b72b525d25.svg</value>
      <webElementGuid>97891ea1-eae1-4455-b1b5-ff1cadd3717b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>imgSrc</value>
      <webElementGuid>ec1a6212-927b-4a11-ad58-63979ba5fbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://aadcdn.msftauth.net/shared/1.0/content/images/picker_account_add_77a852ed38516108ced087b72b525d25.svg</value>
      <webElementGuid>ff96a503-5c89-495d-9015-19265042f713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherTile&quot;)/div[@class=&quot;table-row&quot;]/div[@class=&quot;table-cell tile-img&quot;]/img[@class=&quot;tile-img&quot;]</value>
      <webElementGuid>a395fbe8-6eca-42c0-90dc-244ad9c83fe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherTile']/div/div/img</value>
      <webElementGuid>4e4ed032-1b6d-4250-a4b9-a5b465ad4729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://aadcdn.msftauth.net/shared/1.0/content/images/picker_account_add_77a852ed38516108ced087b72b525d25.svg')]</value>
      <webElementGuid>b1c4ca08-77cd-4fe1-8e7b-1b7bc3f034e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>6260ea35-d405-4c8c-a577-7acebf83c05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://aadcdn.msftauth.net/shared/1.0/content/images/picker_account_add_77a852ed38516108ced087b72b525d25.svg']</value>
      <webElementGuid>4ec28836-25ee-4941-b077-07ab07ffbc9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
